# Generated by Django 5.2 on 2025-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
    ]
