# Generated by Django 5.2 on 2025-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
    ]
