# Generated by Django 5.2 on 2025-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_remove_course_summary_es_remove_course_summary_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary_uk",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_uk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_uk",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_uk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_uk",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
