# Generated by Django 5.2 on 2025-05-30 07:44

from django.db import migrations
from django.utils.text import slugify

def ensure_video_slugs(apps, schema_editor):
    UploadVideo = apps.get_model('course', 'UploadVideo')
    for video in UploadVideo.objects.all():
        if not video.slug:
            # Generate slug from title to ensure uniqueness
            base_slug = slugify(video.title)
            # Ensure uniqueness by adding a number if needed
            slug = base_slug
            counter = 1
            while UploadVideo.objects.filter(slug=slug).exclude(pk=video.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            video.slug = slug
            video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_summary_es_remove_course_summary_fr_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_video_slugs),
    ]
