# Generated by Django 5.2 on 2025-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_choice_choice_text_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="choice_text_uk",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_uk",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_uk",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_uk",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
    ]
