# Generated by Django 5.2 on 2025-05-09 09:28

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
    ]
